name: Build Godot Project for Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Export the project for Windows
      - name: Export Windows Build
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          export_preset: "Windows Desktop"
          archive_output: true

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: ${{ steps.export.outputs.archive_directory }}/*